### ISSUE TITLE
pygmsh how to open an .stl file and create a volumetric mesh

### ISSUE THREAD

**Issue by SaimaSafdar** [nschloe/pygmsh#279]
Hi nschloe,
I am new to pygmsh. Actually I need to open the .stl file. I need to read the geometry in the file and create a mesh out of that geometry. is it possible to do it using pygmsh. Previously I used gmsh-api not pygmsh and it worked well as it offers open, merge, write, addvolume , addsurfaceloop directly to the geometry opened.

could you please help in this regard.

thankyou

**Comment by nschloe** [comment]
It's not possible yet; I wouldn't mind adding the functionality though. Can you post a _simple_ gmsh code that you used, along with a _simple_ STL geometry?

**Comment by SaimaSafdar** [comment]
I used the gmsh-api for python https://gitlab.onelab.info/gmsh/gmsh/blob/master/README.txt 
The code I used is below for the gmsh-api

import math
import gmsh_api
import gmsh_api.gmsh as gmsh

gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 1)
gmsh.option.setNumber("Mesh.Algorithm", 8);
gmsh.option.setNumber("Mesh.CharacteristicLengthMin", 1);
gmsh.option.setNumber("Mesh.CharacteristicLengthMax", 2);
gmsh.option.setNumber("Mesh.Optimize",1)
gmsh.option.setNumber("Mesh.QualityType",2);

gmsh.merge("C:/2_FuzzyClassification/brainmodel/brainModelscriptacvd.stl")
n = gmsh.model.getDimension()
s = gmsh.model.getEntities(n)
l = gmsh.model.geo.addSurfaceLoop([s[i][1] for i in range(len(s))])
gmsh.model.geo.addVolume([l])
print("Volume added")
gmsh.model.geo.synchronize()

gmsh.model.mesh.generate(3)
gmsh.write("C:/2_FuzzyClassification/brainmodel/example.msh")
gmsh.finalize()

the code works fine but I need to use pygmsh api instead of gmsh-api. I am using it inside slicer3d and it has issues (gmsh-api)

**Comment by sampotter** [comment]
I would love for this to be supported as well. Loading a surface mesh and generating a volume mesh from it is arguably the most common use case for this library.

I'm still learning gmsh itself, but if adding support for this is straightforward, I'm happy to try to help.

**Comment by gdmcbain** [comment]
Translating the code of @SaimaSafdar into pygmsh looks reasonably straightforward, but, as asked previously, would it be possible to post a simple STL geometry?

**Comment by sampotter** [comment]
Here you go.

[sample.stl.zip](https://github.com/nschloe/pygmsh/files/4061888/sample.stl.zip)

**Comment by gdmcbain** [comment]
As a preliminary step, I wrote a GEO script.
```c++
Merge "sample.stl";
ClassifySurfaces{Pi/4, 0, 1};
CreateGeometry;
Surface Loop(1) = Surface{:};
Volume(1) = {1};
```
which with 
```shell
gmsh -3 sample.geo
```
produces [sample.msh.zip](https://github.com/nschloe/pygmsh/files/4061921/sample.msh.zip) which looks O. K.:
![sample](https://user-images.githubusercontent.com/1588947/72388599-7b285500-377a-11ea-99c1-0090116eaee0.png)

Next: translate the GEO into pygmsh.  Of course this is always possible with the use of [`add_raw_code`](https://github.com/nschloe/pygmsh/blob/d6eebb4b3be876fa25b18f67358c26611b212104/pygmsh/built_in/geometry.py#L548-L557); e.g.
```
from pygmsh.built_in import Geometry
from pygmsh import generate_mesh

geom = Geometry();
geom.add_raw_code('Merge "sample.stl";')
geom.add_raw_code('ClassifySurfaces{Pi, 0, 1};')
geom.add_raw_code('CreateGeometry;')
geom.add_raw_code('Surface Loop(1) = Surface{:};')
geom.add_raw_code('Volume(1) = {1};')

with open('generated.geo', 'w') as fout:
    fout.write(geom.get_code())
    fout.write('\n')
```

but unfortunately I'm not sure that we can do any better than that here for now:
*  `Merge` isn't implemented.
* `ClassifySurfaces` isn't implemented.
* `CreateGeometry` isn't implemented.
* `The colon operator that indicates all the surface-identifiers isn't implemented and we have no way of knowing how many surfaces the STL will be classified into.
* We can't use `add_volume` since that needs on the right-hand side not just the int 1 but a `SurfaceLoop` and we don't have that since we used raw GEO code to generate the Surface Loop in the previous line.

Not looking good.  A lot of these hurdles are fundamental to the pygmsh approach, so far as I can see; since pygmsh is just generating GEO code and not actually running Gmsh internally, it has to predict the outcome of various Gmsh operations like `ClassifySurfaces`.  That's probably not realistic.

**Comment by nschloe** [comment]
FWIW, I'm always using pygalmesh to create volume meshes from surfaces, https://github.com/nschloe/pygalmesh#volume-meshes-from-surface-meshes.

**Comment by tcaduser** [comment]
> FWIW, I'm always using pygalmesh to create volume meshes from surfaces, https://github.com/nschloe/pygalmesh#volume-meshes-from-surface-meshes.

Is it possible to have a sizing field specified at the vertices of a background volumetric mesh?

**Comment by sampotter** [comment]
@nschloe Thanks for the reference. Since it seems like you've extensively used both both CGAL's 3D meshing and gmsh, would you mind sharing your thoughts on how the two compare? I initially was leaning towards gmsh because it felt "high-performance" (although, I don't have any hard numbers or comparisons with other meshing software to back this up in a meaningful way), but the bad UI and bad scripting language have been a non-starter.

**Comment by nschloe** [comment]
Both packages are way harder to use than they should be, but that's the current state of meshing. pygmsh and pygalmesh exist for no other reason. "Performance" in mesh generation has hardly ever been an issue for me; the PDEs I'm trying to solve on the generated meshes are typically _much_ harder.

**Comment by nschloe** [comment]
> Is it possible to have a sizing field specified at the vertices of a background volumetric mesh?

In pygalmesh? Not yet.

**Comment by nschloe** [comment]
pygmsh uses the gmsh python API, and you can mix and match the two. Your code would look something like this:
```python
import gmsh
import pygmsh

with pygmsh.geo.Geometry() as geom:
    gmsh.option.setNumber("Mesh.CharacteristicLengthMin", 1)
    gmsh.option.setNumber("Mesh.CharacteristicLengthMax", 2)
    gmsh.option.setNumber("Mesh.Optimize", 1)
    gmsh.option.setNumber("Mesh.QualityType", 2)

    gmsh.merge("C:/2_FuzzyClassification/brainmodel/brainModelscriptacvd.stl")
    n = gmsh.model.getDimension()
    s = gmsh.model.getEntities(n)
    l = gmsh.model.geo.addSurfaceLoop([s[i][1] for i in range(len(s))])
    gmsh.model.geo.addVolume([l])

    mesh = geom.generate(dim=3, verbose=True, algorithm=8)

mesh.write("out.vtk")
```

**Comment by xuhenry** [comment]
@nschloe 
There is an Error, when I perform the previous script,:AttributeError: 'Geometry' object has no attribute 'generate'

**Comment by nschloe** [comment]
It should have been `generate_mesh`; fixed in the example.

**Comment by xuhenry** [comment]
@nschloe  Hello, when I change the size of the mesh, why there is no changes on the mesh size of boundary (the facet of the stl).
Thanks a lot!

**Comment by renjiaren** [comment]
@xuhenry I have the same problem. Have you solved it?

**Comment by amul2001** [comment]
Not yet bruh..
