### ISSUE TITLE
Insert point with OpenCascade engine

### ISSUE THREAD

**Issue by dptreurniet** [nschloe/pygmsh#337]
I'm using the module to generate meshes for finite element method work. I would like to insert points in a 2D geometry to ensure that mesh nodes will be placed at these locations. Is this possible when using the OpenCascade engine?

**Comment by nschloe** [comment]
Best find out how to do this in gmsh. Then you can use `add_raw_code`, or we find a "nicer" way handle it.

**Comment by tayebzaidi** [comment]
I was looking for how to do this as well, and found [this](https://stackoverflow.com/questions/36338025/how-to-ensure-node-points-in-gmsh) stackexchange suggestion.
It seems Gmsh has syntax for doing just this in the form of 
`Point{name} In Surface Surface{name}`
I couldn't find any reference to this syntax in the pygmsh codebase, so it may be something useful to add on.

**Comment by nschloe** [comment]
Definitely. PRs welcome.

**Comment by tayebzaidi** [comment]
I'm working on making a PR for this functionality, however I run into difficulties if I try to add the raw code after a boolean operation has been conducted.  The problem seems to be a syntax error with the boolean result ID.  Is there a reason why the results of boolean operations have the name followed by `[]` (e.g. `bo1[]`)?  

When I remove the brackets, gmsh does not throw a syntax error and I can successfully use the above functionality.  I can also make a separate issue for this if you think that would be more clear.

**Comment by nschloe** [comment]
Do the tests pass if the brackets are removed? That'd be fine then.

**Comment by tayebzaidi** [comment]
Yes, I ran pytest on the root directory and the only test that failed was the test_readme.py

**Comment by nschloe** [comment]
Ah, I think the last one is because of a dependency mismatch. Let me fix this real quick.

**Comment by nschloe** [comment]
Okay, merge master and try again. You can submit a PR straight away.

**Comment by nschloe** [comment]
Fixed by #348.
