### ISSUE TITLE
not always importing gmsh

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#380]
While importing the Gmsh Python API is a very good idea, one that I've been thinking about for years, offering much more introspective power than the simple pygmsh<7 GEO code generation, the latter did suffice for a lot of tasks for a long time and occasionally it might be awkward to have to try to set up Gmsh so that `import gmsh` works, as opposed to just having the Gmsh binary on the `PATH` so that it can be called to read the GEO and produce MSH 4.1.  For systems on which `pip install gmsh` works, all good, but I'm reading that that doesn't always work because it brings in a Gmsh with many dependencies.

I'm wondering whether the old 6.1.1 `built_in` and `opencascade` modules might be revived and put alongside the new `geo` and `occ` modules, to give 2x2=4 subclasses of Geometry, two importing `gmsh` and two not.

It's a bit fiddly having 6.1.1 and 7 installed in the same venv or conda env.  (Actually I don't know how to do that.)  I have much legacy code depending on pygmsh<7 but having code that runs in either 6.1.1 or 7 seems tricky.  That is, it might be nice to be able slowly migrate the legacy code to the new gmsh-importing modules over time, and particularly in order to make use of the new facilities that they offer.

**Comment by nschloe** [comment]
> one that I've been thinking about for years

Same. The reason why I did it now was that I needed mesh refinement where the mesh size was given by a (Python) function. This wasn't possible when writing a geo file first of course. I'm all around pretty happy how it turned out, the code is much cleaner now.

I'm not planning to support the command-line version anymore, it'd simply be too much maintenance burden for me with a questionable benefit. I'd advice everyone who really needs the command-line version to use pygmsh 6 or below.
