### ISSUE TITLE
accept expressions for Physical entity identifiers

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#46]
This picks up a tangent from #19 .  That was originally about the _expression-list_ in the right-hand side of the constructor for a `Physical` entity but  @beckerrh also raised there a related issue about the left-hand side only accepting a _char-expression_ whereas according to e.g. [§5.5.1 Points](http://gmsh.info/doc/texinfo/gmsh.html#index-Physical-points) the syntax is 

> Physical Point ( expression | char-expression <, expression> ) <+|->= { expression-list }; 

i.e. it should also accept an _expression_, where 'The expression inside the parentheses is the physical point’s identification number'.

This is trivially exemplified in the same snippet from [t1.geo](https://onelab.info/svn/gmsh/trunk/tutorial/t1.geo) that I used to open #19:

    Physical Point(1) = {1,2} ;

So the answer to the query of @nschloe 

> @beckerrh Is this really supported? I only ever see strings as Physical labels.

is yes, numerically valued non-char-expression expressions are supported for Physical labels in Gmsh and maybe should be in pygmsh to.

**Comment by nschloe** [comment]
The problem here is another gmsh oddity: When using a string from a `Physical`, an integer gets assigned to it in the background. This
```
Physical Surface("dummy") = {s0};
Physical Surface(1) = {s1};
```
will fail with
```
Error   : '/tmp/tmpgGBScU.geo', line 35 : Physical surface 1 already exists
```
Message: Setting the index yourself can lead to unexpected errors.

To avoid such issues, pygmsh keeps track of the index. If you don't provide `label` to `add_physical_*`, it'll choose the next available integer for you, such that nothing can fail.

Alright, so what we could do is to allow integers and `assert` in pygmsh that it's not a label that's already taken.

**Comment by nschloe** [comment]
Fixed now.
